README.md
docs: 命令`go build .`构建产物名字为项目名即paopao-ce，故调整编译命令为`go build -o paopao-api .`
=> docs: 命令`go build .`构建产物名字为项目名即paopao-ce

go.mod, go.sum, pkg/util/ip.go, pkg/util/iploc/iploc.go, pkg/util/iploc/iploc_test.go
* go:embed 内嵌qqwry.dat
* 内部实现ip地址信息查找逻辑，替换github.com/yinheli/qqwry
为什么要替换github.com/yinheli/qqwry？
这个库的Find(...) 每次调用都需要打开qqwry.dat进行数据查找，对于一个不变的静态数据，这是没必要的，这个函数调用的频次也很高，值得优化！
=> 优化查找IP地址信息的逻辑

init.go, internal/routers/api/attachment.go, internal/routers/api/comment.go, internal/routers/api/home.go, internal/routers/api/message.go, internal/routers/api/post.go, internal/routers/api/user.go, internal/service/attachment.go, internal/service/avatar.go, internal/service/comment.go, internal/service/message.go, internal/service/post.go, internal/service/service.go, internal/service/sign.go, internal/service/user.go, internal/service/wallet.go, pkg/zinc/zinc.go
* 优化service包的代码，直接导出功能函数
补丁主要优化什么?
```
// file: internal/routers/api/user.go
// 用户登录
func Login(c *gin.Context) {
...
svc := service.New(c)
user, err := svc.DoLogin(&param)
...
}
// 用户注册
func Register(c *gin.Context) {
...
svc := service.New(c)
err := svc.ValidUsername(param.Username)
...
err = svc.CheckPassword(param.Password)
...
}
// 修改密码
func ChangeUserPassword(c *gin.Context) {
...
svc := service.New(c)
err := svc.CheckPassword(param.Password)
...
}
```
参考上面代码， 每次Restful请求都需要重新创建一个`service.Service`实例，但该实例包含的内容除了每次请求的 `c *gin.Context`外，其他内容都是不变的(结构内field 变量 `dao *dao.Dao` 其实每次创建都是用相同配置重新实例化一个对象)，也就是说，完全可以在对应的函数中按需传入`c *gin.Context`，不同功能函数内使用同一个不变的 `dao *dao.Dao` 完成业务逻辑。  
这个补丁的核心目标就是干掉 api函数里的 `svc := service.New(c)` 变成如下代码 :  
```
// file: internal/routers/api/user.go
// 用户登录
func …
```
=> optimize code in internal/service pacakge

Makefile, README.md, build.sh, internal/routers/router.go, internal/routers/statick.go, internal/routers/statick_embed.go, web/.gitignore, web/embed.go, web/src/api/auth.ts, web/src/api/post.ts, web/src/api/user.ts
1. move all api to v1 group
2. web ui adapt all api to v1 group
3. support embed web ui to server if needed
支持直接把Web UI资源嵌入到可执行文件，方便部署(只需要一个可执行文件+配置文件就可以完成前端、后端部署)。
考虑到有可能需要内嵌Web UI资源，顺手把API接口版本化，这也方便以后进行版本化API接口按需调用。
=> move all api to v1 group and suport embed web ui to server

README.md, web/src-tauri/Cargo.toml, web/src-tauri/src/main.rs
* remove submenu in window when not on MacOS platform
桌面端: 在Linux(Debian/Ubuntu/Fedora)、Windows平台下去掉菜单栏，界面看起来更加干净。
=> desktop/tauri: remove submenu in window when not on MacOS platform

internal/core/cache.go, internal/core/core.go, internal/core/search.go, internal/core/storage.go, internal/core/wallet.go, internal/dao/attachment.go, internal/dao/comment.go, internal/dao/comment_content.go, internal/dao/dao.go, internal/dao/message.go, internal/dao/post.go, internal/dao/post_content.go, internal/dao/search.go, internal/dao/tag.go, internal/dao/user.go, internal/dao/wallet.go, internal/routers/api/post.go, internal/service/attachment.go, internal/service/comment.go, internal/service/message.go, internal/service/post.go, internal/service/service.go, internal/service/user.go, internal/service/wallet.go
* make abstract backend process logic to service interface
这个PR解决什么问题?
pr主要是把后端的数据处理逻辑接口化、服务化，定义好需要的数据处理逻辑接口，按需要的场景实现对应的服务接口，然后通过统一的函数导出接口服务。
为什么要把后端数据处理逻辑服务接口化？
1. 方便集成测试、模糊测试； 处理逻辑接口化后，编写测试用例时，可以专门针对测试用例实现服务接口，完成对应的功能测试，当然目前还没怎么写测试用例，但是后续应该会跟上这部分工作。
2. 方便服务扩展。例如：图片存储服务，目前用的是阿里的AliOSS，如果需要使用其他的对象存储服务，比如腾讯云、华为云的对象存储服务或者自己搭建的MINIO等，只要实现一个定义好的存储服务接口(其内部实现适配对应的底层对象存储服务)，就可以在程序启动时就可以根据配置按需去实例化相应的存储服务。
4. 为功能扩展做准备，比如图片存储支持腾讯云、MINIO等。
后端数据处理逻辑服务接口化的优缺点?
优点: 接口清晰、可扩展性好；
缺点: 代码编写有点繁琐，需要定义接口、编写实现、导出服务等。
总的来说，面向接口编程还是一种比较好的编程范式。
=> optimize: abstract backend process logic to service interface

config.yaml.sample, global/setting.go, init.go, internal/dao/user.go, internal/model/model.go, internal/routers/api/attachment.go, internal/routers/api/user.go, internal/service/comment.go, internal/service/post.go, internal/service/service.go, internal/service/user.go, pkg/logger/logger.go, pkg/setting/seting_test.go, pkg/setting/settting.go, pkg/zinc/zinc.go
* support composite feature that server supported just by configure file
1. pr优化什么？
补丁优化app配置的使用机制，支持通过配置文件配置app运行时提供哪些功能。
```yaml
...
Features:
Default: ["Sms", "Alipay", "Zinc", "MySQL", "Redis", "AliOSS", "LoggerZinc"]
Develop: ["Zinc", "MySQL", "AliOSS", "LoggerFile"]
Slim: ["Zinc", "MySQL", "Redis", "AliOSS", "LoggerFile"]
Sms: "SmsJuhe"
...
SmsJuhe:
Key:
TplID:
TplVal: "#code#=%d&#m#=%d"
```
如上：在`Features` section 是配置app的一些功能项配置组合，`Default` `Develop` `Slim`是不同的运行时功能组合，`Sms/Alipay/Zinc/MySQL/Redis/AliOSS/LoggerZinc/LoggerFile`是目前app程序能提供的功能，通过配置不同的功能组合，在app运行时传参告知运行那种组合，比如：
```sh
paoapo-ce
```
运行默认`Default`的Features组合；
```sh
paopao-ce --no-default-features --features Develop
```
运行 `Develop` 的Features组合(cli 选项这个功能后续加上)。
2. 为什么提供这个功能？
方便添加不同的功能，比如SQL存储可以支持Postgres/sqlite3, …
=> support composite feature that server supported just by configure file

internal/dao/cache_index.go
* fixed cache index calculate offset/limit error
=> fixed cache index calculate offset/limit error

pkg/util/iploc/iploc.go
当ip为ipv6本地地址时，`net.ParseIP(ip).To4()`返回nil，然后`binary.BigEndian.Uint32(nil)`会报错。
所以，应该考虑nil的情况
=> ipv6本地地址上传图片报错

README.md, config.yaml.sample, docker-compose.yaml
update docker-compose.yaml localoss instead minio as object storage and add phpmysqladmin as db manager
=> docker-compose localoss instead minio as object storage and add phpmysqladmin as db manager

README.md, config.yaml.sample, go.mod, go.sum, internal/conf/conf.go, internal/conf/settting.go, internal/core/cache.go, internal/core/version.go, internal/dao/cache_index_big.go, internal/dao/cache_index_simple.go, internal/dao/dao.go, internal/dao/post_index.go, internal/routers/api/post.go, internal/routers/api/user.go, internal/routers/router.go, internal/service/post.go
* add BigCacheIndex for cache index posts
提供另一个名为`BigCacheIndex`的 广场推文列表 缓存器，内部实现基于[BigCache](https://github.com/allegro/bigcache)，可以做到按 每用户-每分页 的细粒度缓存，同时也为未来 按不同用户查询到的 广场推文列表 提供缓存，可以简单做到千人千面，比如 登入用户 广场页面显示 公开+好友可见推文， 没登入用户仅显示 公开可见 推文， 当然这些目前由于还没有建立起好友体系，所以暂时埋坑占位还没有实现，但是这个 缓存器 提供缓存不同用户不同页面的能力可以潜在的支撑简单千人千面的缓存实现。
```yaml
...
Features:
Default: ["Base", "Sqlite3", "BigCacheIndex", "MinIO", "LoggerZinc"]
...
BigCacheIndex: # 使用BigCache缓存泡泡广场消息流
MaxIndexPage: 1024          # 最大缓存页数，必须是2^n, 代表最大同时缓存多少页数据
Verbose: False              # 是否打印cache操作的log
ExpireInSecond: 300         # 多少秒(>0)后强制过期缓存
UpdateQPS: 100              # 添加/删除/更新Post的QPS, 默认100
...
```
Features中加入`BigCacheIndex` 功能项，并配置对应的参数。
=> add BigCacheIndex for cache index posts

Dockerfile, README.md, config.yaml.sample, docker-compose.yaml, go.mod, go.sum, internal/conf/conf.go, internal/conf/logger.go, internal/conf/logger_meili.go, internal/conf/logger_zinc.go, internal/conf/settting.go, internal/dao/search.go, internal/dao/search_meili.go, internal/dao/search_zinc.go, internal/service/post.go, pkg/zinc/zinc.go
* support meilisearch as tweet search service
pr特性:
支持基于[meilisearch](https://github.com/meilisearch/meilisearch)引擎提供推文搜索服务。
目前状态：
这个pr不影响原有zinc提供的推文搜索服务，可以通过配置文件切换使用zinc/meili:
```yaml
Features:
Default: ["Base", "Sqlite3", "BigCacheIndex", "Meili", "MinIO", "LoggerZinc"]
```
> 文档README已经注明 Meili/LoggerMeili 目前状态为内测阶段，产品部署推荐使用Zinc；
=> support meilisearch as tweet search service

README.md, internal/core/authority.go, internal/core/index.go, internal/core/search.go, internal/dao/authority.go, internal/dao/cache.go, internal/dao/cache_index_big.go, internal/dao/cache_index_simple.go, internal/dao/dao.go, internal/dao/post_index.go, internal/dao/search.go, internal/dao/search_bridge.go, internal/dao/search_filter.go, internal/dao/search_meili.go, internal/dao/search_zinc.go, internal/model/model.go, internal/model/post.go, internal/routers/api/post.go, internal/service/post.go, pkg/types/types.go
* support search private tweet and display private tweet in index page when user login or is admin
支持搜索私密推文。
=> support search private tweet

Makefile, README.md, config.yaml.sample, go.mod, go.sum, internal/conf/conf.go, internal/conf/settting.go, internal/dao/dao.go, internal/dao/storage/huaweiobs.go, internal/dao/storage/storage.go
* support Huawei Cloud OBS as OSS service
=> support Huawei Cloud OBS as OSS service

web/src/views/Home.vue
* web: just reload home path after create post success
pr概述：
在泡泡广场页面 成功创建推文后，页面跳转到泡泡详情页面，然后从泡泡详情页面返回到广场页面(点按页面中的返回上一级按钮或直接浏览器的返回按钮)，文章列表并没有自动刷新到最新状态，需要额外的刷新操作才能更新文章列表。 用户应该期望的是返回到广场页面后文章列表能自动刷新到最新状态； 这里有两种改法：   
1.  从泡泡详情页面返回到泡泡广场页面后自动刷新文章列表到最新状态；
2. 创建推文后，直接重新加载文章列表到最新状态，不自动跳转到泡泡详情页面；
pr特性：
如上所述，这个pr采用第二种方案解决上述问题。 
* 不太清楚设计之初为什么要在创建推文成功后跳转到泡泡详情页面，但是从我个人使用体验，每次创建推文后，第一件事是顺手返回到泡泡广场页面，因为刚创建的推文泡泡详情页面除了推文内容，啥也没有（点赞/收藏/评论）并不想在这个页面多待，所以在想是不是成功创建推文后留在泡泡广场页面会更好一点呢，这个pr基于这一点优化上述问题。 
* 如果设计需要在创建推文成功后跳转到泡泡详情页，这个pr就不要合并了，可以采用上述第一种方案另外提一个PR优化用户体验。
=> web: just reload home path after create post success

internal/service/post.go
* optimize create post logic simple to simple
=> optimize create post logic simple to simple

web/src/views/Home.vue
* web: go to post detail page if main page not at first when create post success
=> web: go to post detail page if main page not at first when create post success

internal/dao/storage/localoss.go
* feature[oss:tempdir]  fixed persist object failed error in localoss implement
just bugfix for oss:tempdir feature in localoss implement.
=> fixed persist object failed error in localoss oss:tempdir implement

internal/dao/cache/base.go
* fixed cache index not expire in delete/add tweet error
pr特性：
* 修复广场推文列表缓存在添加删除推文后没有立即失效的问题，这会导致让用户以为添加/删除推文不成功的错觉，这个bug是之前引入`RedisCacheIndex`功能项时一个小失误导致的，这个补丁用于修复这个bug。
> 这个bug对用户体验影响很大，算是比较严重的bug。
=> fixed cache index not expire in delete/add tweet error

CHANGELOG.md, auto/api/v1/loose.go, auto/api/v1/pub.go, internal/core/comments.go, internal/dao/jinzhu/comments.go, internal/model/web/loose.go, internal/model/web/pub.go, internal/servants/web/loose.go, internal/servants/web/pub.go, mirc/web/v1/loose.go, mirc/web/v1/pub.go
* fixed comments thumbs up/down state incorrect erro
=> fixed comments thumbs up/down state incorrect erro

internal/servants/web/utils.go, web/src/components/compose.vue, web/src/utils/isZipFile.ts
今天在windows10的google chrome上上传zip文件，无法上传，检查是MimeType不兼容，可参考文章说明:
https://qa.1r1g.com/sf/ask/59920941/
这个commit用于处理zip文件的兼容性MimeType检测
=> bugfix: Compatible with different browsers for uploading zip mimetype

.github/workflows/go.yml, .gitignore, CHANGELOG.md, Dockerfile, Makefile, README.md, build-release.sh, cmd/migrate/migrate.go, cmd/root.go, cmd/serve/serve.go, cmd/version.go, go.mod, go.sum, internal/servants/statick/statick.go, internal/servants/statick/statick_embed.go, main.go, pkg/version/version.go, web/embed.go
- add cli subcommand to start paopao-ce serve or other task.
- optimize embed web ui to paopao execute binary file logic.
=> add cli subcommand to start paopao-ce serve

CHANGELOG.md, README.md, docker-compose.yaml, features-status.md, internal/conf/conf.go, internal/conf/config.yaml, internal/conf/logger.go, internal/conf/logger_observe.go, internal/conf/setting.go, internal/dao/search/bridge.go, pkg/http/client.go, pkg/http/http.go, pkg/obx/obx.go
- add `LoggerOpenObserve` feature use OpenObserve to collect log.    
add `LoggerOpenObserve` to `conf.yaml` 's `Features` section to enable this feature like below:
```yaml
...
Features:
Default: ["Base", "Postgres", "Meili", "LocalOSS", "LoggerOpenObserve", "BigCacheIndex", "web"]
LoggerOpenObserve: # 使用OpenObserve写日志
Host: 127.0.0.1:5080
Organization: paopao-ce
Stream: default
User: root@paopao.info
Password: tiFEI8UeJWuYA7kN
Secure: False
MinWorker: 5               # 最小后台工作者, 设置范围[5, 100], 默认5
MaxLogBuffer: 100          # 最大log缓存条数, 设置范围[10, 10000], 默认100
...
=> add LoggerOpenObserve feature to use OpenObserve collect log

internal/dao/storage/minio.go
现象：存储 minio， post 带有多张图片，删除post，多张图片仍在minio内，无法删除
参考官方用法：
https://github.com/minio/minio-go/blob/master/examples/s3/removeobjects.go
pr 修复了 minio 多文件删除的问题
=> fix minio removeobjects

web/src/components/main-nav.vue
看这个这个黑暗模式的图标感觉怪怪的
感觉像是反了
不晓得是不是设计如此
=> Update main-nav.vue modify dark light icon position

internal/dao/jinzhu/topics.go
The intention here should be to initialize a slice with a capacity of len(tagMap) rather than initializing the length of this slice.
=> fix: fix slice init length
