rocboss/paopao-ce

- web/src/api/auth.ts
- web/src/api/post.ts
- web/src/api/user.ts
- web/src/components/comment-item.vue
- web/src/components/compose-comment.vue
- web/src/components/compose.vue
- web/src/components/post-attachment.vue
- web/src/components/post-detail.vue
- web/src/components/post-image.vue
- web/src/components/post-item.vue
- web/src/components/post-link.vue
- web/src/components/post-video.vue
- web/src/types/NetParams.d.ts
- web/src/types/NetReq.d.ts
- web/src/types/item.d.ts
- web/src/utils/request.ts
- web/src/views/Post.vue
- web/src/views/Setting.vue
> feat: fix typescript

- Makefile
* just `make run`  to start server
> just `make run`  to start server

- web/src-tauri/tauri.conf.json
* change desktop app title same as web
> change desktop app title same as web

- internal/routers/api/attachment.go
> fixed issues #58 that upload attachment failure

- internal/routers/api/attachment.go
> add miss fixed for #58

- README.md
* remove storage directory 
storage directory is runtime enviroment output directory that configure from config.yaml if needed, no need keep in source repository.
> remove no need directory and files

- .gitignore
- Dockerfile
- README.md
- config.yaml.sample
- docker-compose.yaml
* add docker-compose support
use docker-compose just one command use default configure:
```sh
%> docker compose up --build
```
> add docker-compose support

- config.yaml.sample
- docker-compose.yaml
* optimize docker-compose config to export backend to out network
> optimize docker-compose config to export backend to out network

- config.yaml.sample
- internal/conf/conf.go
- internal/conf/settting.go
- internal/dao/cache_index.go
- internal/dao/dao.go
optimize #78 change CacheIndex configure in conf.yaml to SimpleCacheIndex
> optimize #78 change CacheIndex in conf.yaml to SimpleCacheIndex

- config.yaml.sample
- internal/conf/settting.go
- internal/dao/cache_index.go
* optimize #78 support custom configure ActionQPS to adjust internal action event send
> optimize #78 support custom configure ActionQPS

- internal/core/cache.go
- internal/core/core.go
- internal/core/index.go
- internal/dao/cache_index.go
- internal/dao/post_index.go
abstract IndexPostsService interface for get index posts
> abstract IndexPostsService interface for get index posts

- internal/dao/user.go
> merge from dev branch

- Makefile
- main.go
* remove no-need build version info
> remove no-need build version info

- README.md
* update README.md add features configure help doc
> update README.md add features configure help doc

- web/src/views/Collection.vue
* fixed collection page's pagination item to center
> fixed collection page's pagination item to center

- config.yaml.sample
- internal/conf/db.go
- internal/conf/settting.go
- internal/dao/post.go
- internal/model/post_collection.go
- internal/model/post_star.go
- internal/routers/api/post.go
- internal/service/post.go
- internal/service/user.go
* optimize #97 user stars/collections update when post visibility changed
* database level config use human string to set
在推文可见性修改后，同步更新用户收藏/点赞。
> optimize #97 user stars/collections update when post visibility changed

- web/src-tauri/Cargo.toml
- web/src-tauri/tauri.conf.json
* desktop/tauri: disable resizable transparent window and enable setfullscreen on macos
> desktop/tauri: disable resizable transparent window and enable setfullscreen on macos

- internal/service/post.go
* fixed create not expected empty string tag when create post
> fixed create not expected empty string tag when create post

- Makefile
- internal/routers/api/home.go
- main.go
- pkg/debug/version.go
* optimize version info out logic
> optimize version info out logic

- go.mod
- go.sum
- internal/conf/logger.go
- internal/dao/user.go
- internal/service/post.go
- pkg/json/go_json.go
- pkg/json/json.go
- pkg/json/jsoniter.go
- pkg/zinc/zinc.go
* optimize json encoding module that code from gin
> optimize json encoding module that code from gin

- internal/core/cache.go
- internal/core/core.go
- internal/core/search.go
- internal/core/storage.go
- internal/dao/cache.go
- internal/dao/dao.go
- internal/dao/oss.go
- internal/dao/oss_alioss.go
- internal/dao/oss_local.go
- internal/dao/oss_minio.go
- internal/dao/post.go
- internal/dao/post_index.go
- internal/dao/search.go
- internal/dao/search_zinc.go
- internal/routers/api/post.go
- internal/service/post.go
- internal/service/service.go
* optimize search logic to abstract in a new service interface
优化抽象搜索接口， 方便添加不同搜索引擎。
> optimize search logic to abstract in a new service interface

- config.yaml.sample
- internal/conf/conf.go
- internal/conf/settting.go
- internal/core/search.go
- internal/dao/cache_index_big.go
- internal/dao/cache_index_simple.go
- internal/dao/dao.go
- internal/dao/oss.go
- internal/dao/search.go
- internal/dao/search_bridge.go
- internal/dao/search_zinc.go
- internal/routers/api/api.go
- internal/service/comment.go
- internal/service/post.go
- internal/service/service.go
* optimize #118 wrap async interface for update documents to search engine
> optimize #118 wrap async interface for update documents to search engine

- config.yaml.sample
- internal/conf/settting.go
- internal/dao/search.go
- internal/dao/search_bridge.go
* optimize #118 add backend worker update documents to search engine
> optimize #118 add backend worker update documents to search engine

- internal/conf/logger_meili.go
- internal/dao/search_meili.go
optimize #129 use new goroutine handle log in mieliLogHook fire
> optimize #129 use new goroutine handle log in mieliLogHook fire

- internal/conf/logger_meili.go
- internal/dao/search_meili.go
* optimize #129 make tweet search by tag more exact when use meilisearch
> optimize #129 make tweet search by tag more exact when use meilisearch

- README.md
- docker-compose.yaml
* update README.md add dependent component run/config tutoria
> update README.md add dependent component run/config tutoria

- .dockerignore
- README.md
- docker-compose.yaml
- internal/conf/logger_meili.go
- web/.dockerignore
* update README.md add meilisearch ui managing describe
> update README.md add meilisearch ui managing describe

- internal/dao/dao.go
* fixed get index post list error when not user cache index service
> fixed get index post list error when not user cache index service

- internal/dao/search_zinc.go
* optimize #141 fixed zinc search not in expect result
> optimize #141 fixed zinc search not in expect result

- internal/service/post.go
* optimize #141 fixed tweet in correct visibility status after visible tweet
> fixed tweet in correct visibility status after visible tweet 

- internal/dao/cache_index.go
- internal/dao/cache_index_none.go
- internal/dao/cache_index_simple.go
- internal/dao/dao.go
- internal/dao/post.go
- internal/dao/post_index.go
* optimize post cache index service integrate logic
> optimize post cache index service integrate logic

- internal/conf/conf.go
- internal/conf/db.go
- internal/conf/logger.go
- internal/dao/jinzhu/jinzhu.go
- internal/middleware/jwt.go
- main.go
* optimize #148 lazy initial gorm db in first use
> optimize #148 lazy initial gorm db in first use

- internal/routers/api/user.go
- internal/service/user.go
* fixed phone binding always error at first time
> fixed phone binding always error at first time

- main.go
* optimize print fatal info when app run failed
> optimize print fatal info when app run failed

- internal/core/cache.go
- internal/dao/cache/bigcache.go
- internal/dao/cache/cache.go
- internal/dao/cache/none.go
- internal/dao/cache/simple.go
- internal/dao/jinzhu/tweets.go
* optimize BigCacheIndex logic
> optimize BigCacheIndex logic

- internal/core/storage.go
- internal/core/tweets.go
- internal/dao/jinzhu/tweets.go
- internal/dao/jinzhu/utils.go
- internal/dao/storage/alioss.go
- internal/dao/storage/localoss.go
- internal/dao/storage/minio.go
- internal/model/comment.go
- internal/model/comment_content.go
- internal/model/comment_reply.go
- internal/model/post.go
- internal/model/post_content.go
- internal/model/tag.go
- internal/routers/api/post.go
- internal/service/post.go
- internal/service/service.go
> optimize tweet delete logic

- internal/dao/storage/localoss.go
- internal/model/post_content.go
- internal/routers/api/post.go
* optimize #155 add miss method implements for LocalOSS
> optimize #155 add miss method implements for LocalOSS

- internal/dao/dao.go
- internal/routers/api/api.go
- internal/service/service.go
* single intilialize DataService/TweetSearchService/ObjectStorageService
> single intilialize DataService/TweetSearchService/ObjectStorageService

- web/src/vite-env.d.ts
* optimize #160 make env variable correct
> optimize #160 make env variable correct

- internal/middleware/priv.go
* optimize privApi middleware function
> optimize privApi middleware function

- Makefile
* optimize #160 Makefile change
> optimize #160 Makefile change

- web/src/components/compose.vue
* web: optimize tweet link/visibility option display layout
> web: optimize tweet link/visibility option display layout

- web/.env
- web/src/components/post-image.vue
- web/src/vite-env.d.ts
* web: support custom tweet image thumbnail argument in .env/.env.local
> web: support custom tweet image thumbnail argument in .env/.env.local

- internal/migration/migration_embed.go
* change migration table name same table prefix as other table
> change migration table name same table prefix as other table

- README.md
- config.yaml.sample
- internal/conf/conf.go
- internal/conf/settting.go
- internal/core/storage.go
- internal/dao/storage/alioss.go
- internal/dao/storage/cos.go
- internal/dao/storage/huaweiobs.go
- internal/dao/storage/localoss.go
- internal/dao/storage/minio.go
- internal/dao/storage/storage.go
- internal/routers/api/attachment.go
- internal/service/comment.go
- internal/service/post.go
- internal/service/service.go
- internal/service/user.go
* optimize create post/comment logic that tweet type is media contents
> optimize create post/comment logic that tweet type is media contents

- README.md
> just update README

- internal/dao/storage/minio.go
- internal/service/service.go
> just optimize #169

- README.md
- config.yaml.sample
- internal/conf/settting.go
- internal/core/storage.go
- internal/dao/storage/alioss.go
- internal/dao/storage/cos.go
- internal/dao/storage/huaweiobs.go
- internal/dao/storage/localoss.go
- internal/dao/storage/minio.go
- internal/dao/storage/storage.go
* optimize object storage service implement logic
> optimize object storage service implement logic

- config.yaml.sample
* add miss option item in config.yaml.sample
> add miss option item in config.yaml.sample

- internal/dao/storage/localoss.go
* optimize localossObject implement logic
> optimize localossObject implement logic

- internal/service/post.go
- web/src/views/Home.vue
* optimize #176 change reload page logic just for simple
> optimize #176 change reload page logic just for simple

- internal/dao/storage/storage.go
* just fixed S3Service off OSS initialize config error
> just fixed S3Service off OSS initialize config error

- README.md
- docker-compose.yaml
Fix error "repository public.ecr.aws/prabhat/zinc not found: name unknown: The repository with name 'zinc' does not exist in the registry with id 'prabhat'"
> Update ZincSearch Docker Image

- internal/model/post_content.go
> fix bug,PostContent.Format

- .dockerignore
- .gitignore
- README.md
- config.yaml.sample
- internal/conf/settting.go
- internal/routers/api/api.go
- internal/routers/api/user.go
* optimize alipay initial client logic
> optimize alipay initial client logic

- README.md
* update README.md add star-history svg
> update README.md add star-history svg

- internal/model/tag.go
* fixed get wrong tags that quote num is zero error
> fixed get wrong tags that quote num is zero error

- docs/proposal/016-关于使用pyroscope用于性能调试的设计.md
- internal/conf/config.yaml
- internal/conf/settting.go
- internal/dao/cache/cache.go
* optimize BigCacheIndex add HardMaxCacheSize to customer max cache size in runtime
> optimize BigCacheIndex add HardMaxCacheSize to adjust cache size

- Dockerfile
> just optimize Dockerfile

- Makefile
- README.md
- docs/deploy/local/custom/config.yaml
- internal/conf/config.yaml
* update README.md and add docker-compose.yaml to release zip file when publish release
> update README.md and add docker-compose.yaml to release zip file

- CHANGELOG.md
- Makefile
> add CHANGELOG.md

- .gitignore
- CHANGELOG.md
- auto/api/v1/priv.go
- mirc/web/v1/priv.go
* fixed add star to tweet error
> fixed add star to tweet error

- CHANGELOG.md
- internal/dao/jinzhu/dbr/post_collection.go
- internal/dao/jinzhu/dbr/post_star.go
- internal/dao/jinzhu/tweets.go
- internal/servants/web/priv.go
- fixed tweet's owner not allow star/collection action when tweet is private error
- fixed user not list owner's collectioned private tweet error
> fixed private tweet's star/colloect no permission error when it is owner's

- docker-compose.yaml
> v0.3.0 release

- docker-compose.yaml
- just update docker-compose.yaml
> just update docker-compose.yaml

- CHANGELOG.md
- internal/dao/storage/minio.go
- optimized minio removeobjects.
> optimized minio removeobjects

- CHANGELOG.md
- internal/dao/jinzhu/metrics.go
* fixed update user metric incorrect when no user record
> fixed update user metric incorrect when no user record

- internal/servants/web/loose.go
- fixed nil user err in tweet detail logic
> fixed nil user err in tweet detail logic
